version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=secret_key_sistema_colaborativo
      - JWT_EXPIRES_IN=2h
      - UPLOADS_DIR=./uploads
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./database.sqlite:/usr/src/app/database.sqlite
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: